# yamllint disable rule:line-length
name: Deploy to Netlify

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Verify public directory exists
        run: |
          if [ ! -d "public" ]; then
            echo "Error: public/ directory not found"
            exit 1
          fi
          echo "✓ public/ directory verified"

      - name: Install Netlify CLI
        run: npm ci -g netlify-cli || npm install -g netlify-cli --silent

      - name: Deploy to Netlify (non-interactive)
        run: npx netlify-cli deploy --dir=public --prod --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
